// Generated by CoffeeScript 1.6.1

exports.config = {
  server_port: 9000,
  sockets_port: 9001,
  log_level: 3,
  transports: ['websocket', 'htmlfile', 'xhr-polling', 'jsonp-polling'],
  allowedDomains: "*"
};
